[CI] Fix Homebrew installation
`brew install lit` started failing with the following error:

```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3-3.11
Target /usr/local/bin/2to3-3.11
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3-3.11'

To force the link and overwrite all conflicting files:
  brew link --overwrite python@3.11

To list all files that would be deleted:
  brew link --overwrite --dry-run python@3.11
```

I believe that this is caused by
https://github.com/Homebrew/homebrew-core/pull/115343.

My workaround works, but is not pretty and I should find a better
solution.